# Generated by Django 4.2.1 on 2023-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailer", "0005_expense_comments_expense_image_expense_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
