# Generated by Django 4.2.1 on 2023-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailer", "0006_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashcollection",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cashcollection",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashcollection",
            name="due_amount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
