# Generated by Django 4.2.1 on 2023-06-20 19:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("super_admin", "0002_helpsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestNewUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[("DE", "Dealer"), ("RE", "Retailer")], max_length=3
                    ),
                ),
                ("division", models.CharField(blank=True, max_length=125, null=True)),
                ("district", models.CharField(blank=True, max_length=125, null=True)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="helpsupport",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("PR", "Processing"), ("DN", "Done")],
                default="PR",
                max_length=3,
            ),
        ),
    ]
