# Generated by Django 4.2.1 on 2023-07-11 17:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("super_admin", "0003_requestnewuser_alter_helpsupport_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestnewuser",
            name="user_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+8801712345678", max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
