# Generated by Django 4.2.1 on 2023-10-13 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("super_admin", "0004_alter_requestnewuser_user_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="helpsupport",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("PR", "প্রসেসিং"), ("DN", "সম্পন্ন")],
                default="PR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="requestnewuser",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("DE", "ডিলার"),
                    ("RE", "রিটেইলার"),
                    ("DRE", "ডাইরেক্ট রিটেইলার"),
                    ("DSR", "ডেলিভারি সেলস রিপ্রেজেন্টেটিভ"),
                    ("SR", "সেলস রিপ্রেজেন্টেটিভ"),
                    ("CS", "কাস্টমার"),
                    ("AD", "এডমিন"),
                ],
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="DealerCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.company",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("dealer", "company")},},
        ),
        migrations.AddField(
            model_name="company",
            name="dealers",
            field=models.ManyToManyField(
                blank=True,
                related_name="dealer_companies",
                through="super_admin.DealerCompany",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
