# Generated by Django 4.2.1 on 2023-08-05 21:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_userinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="BD", unique=True
            ),
        ),
    ]
