# Generated by Django 4.2.1 on 2023-12-17 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dealer", "0008_voucher_dealer"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSRVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now=True)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField(default=0)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "dsr",
                    models.ForeignKey(
                        limit_choices_to={"is_dsr": True},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dsr_voucher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dealer.product"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="DSRProductWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "dsr",
                    models.ForeignKey(
                        limit_choices_to={"is_dsr": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsr_product_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dsr_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dealer.product"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
