# Generated by Django 4.2.1 on 2023-12-17 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0008_voucher_dealer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dsr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsrproductwallet",
            name="returned_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dsrproductwallet",
            name="dsr",
            field=models.ForeignKey(
                limit_choices_to={"is_delivery_sales_representative": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dsr_product_wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dsrproductwallet",
            name="dsr_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dsr_product",
                to="dealer.product",
            ),
        ),
        migrations.AlterField(
            model_name="dsrvoucher",
            name="dsr",
            field=models.ForeignKey(
                limit_choices_to={"is_delivery_sales_representative": True},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dsr_voucher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dsrproductwallet", unique_together={("dsr_product", "dsr")},
        ),
    ]
