# Generated by Django 4.2.1 on 2023-12-21 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dsr", "0002_dsrproductwallet_returned_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSRSellingVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now=True)),
                ("returned_product", models.IntegerField()),
                ("damage_product", models.IntegerField()),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "dsr",
                    models.ForeignKey(
                        limit_choices_to={"is_delivery_sales_representative": True},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dsr_selling_voucher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dsr.dsrproductwallet",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="DSRSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now=True)),
                ("total_selling_price", models.FloatField(default=0)),
                ("paid_amount", models.FloatField(default=0)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "dsr",
                    models.ForeignKey(
                        limit_choices_to={"is_delivery_sales_representative": True},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dsr_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "DSR Sale", "verbose_name_plural": "DSR Sales",},
        ),
        migrations.CreateModel(
            name="DSRCollections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now=True)),
                ("collected_amount", models.FloatField(default=0)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "dsr",
                    models.ForeignKey(
                        limit_choices_to={"is_delivery_sales_representative": True},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dsr_collection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "DSR Sale", "verbose_name_plural": "DSR Sales",},
        ),
    ]
