# Generated by Django 4.2.1 on 2023-12-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsr", "0003_dsrsellingvoucher_dsrsales_dsrcollections"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dsrcollections",
            options={
                "verbose_name": "DSR Collection",
                "verbose_name_plural": "DSR Collections",
            },
        ),
    ]
