# Generated by Django 4.2.1 on 2023-12-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsr", "0005_dsrsellingvoucher_sold_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsrsales", name="discount", field=models.FloatField(default=0),
        ),
    ]
