# Generated by Django 4.2.1 on 2024-01-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsr", "0006_dsrsales_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsrsellingvoucher",
            name="original_selling_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="dsrvoucher",
            name="original_selling_price",
            field=models.FloatField(default=0.0),
        ),
    ]
