# Generated by Django 4.2.1 on 2023-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0002_dealerexpense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="dealer_buying_price", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="dealer_selling_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("carton", "কার্টুন"), ("case", "কেস"), ("package", "পলি")],
                default="carton",
                max_length=10,
            ),
        ),
    ]
