# Generated by Django 4.2.1 on 2023-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0003_alter_product_dealer_buying_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock", name="price", field=models.FloatField(default=0),
        ),
    ]
