# Generated by Django 4.2.1 on 2023-10-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0004_stock_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="stock", name="price",),
        migrations.AddField(
            model_name="voucher", name="price", field=models.FloatField(default=0),
        ),
    ]
