# Generated by Django 4.2.1 on 2023-11-23 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealer', '0005_remove_stock_price_voucher_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activated', 'সক্রিয়'), ('deactivated', 'নিষ্ক্রিয়'), ('requested', 'অনুরোধ')], max_length=13)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dealer', models.ForeignKey(limit_choices_to={'is_dealer': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='dealer_representative', to=settings.AUTH_USER_MODEL)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_dealer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
