# Generated by Django 4.2.1 on 2023-11-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_dealerrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
