# Generated by Django 4.2.1 on 2023-12-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0010_damagestock_dealer"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagestock",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
