# Generated by Django 4.2.1 on 2024-01-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0012_alter_damagestock_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voucher", old_name="price", new_name="original_buying_price",
        ),
        migrations.AddField(
            model_name="damagestock",
            name="original_buying_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="damagestock",
            name="original_selling_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="voucher",
            name="original_selling_price",
            field=models.FloatField(default=0.0),
        ),
    ]
